### ISSUE TITLE
Starting todo list

### ISSUE THREAD

**Issue by Blade2021** [Blade2021/Sherlock#2]
- [x] Finish Language filtering commands
- [ ] Add timed bans to system
- [x] SQL Database bug
- [x] Welcome message?
- [ ] Allow up to 10 custom triggers with specified information.
- [x] Add mod role system
- [x] Command data
- [ ] Help system
- [ ] Trigger onMessageDelete (see if message was part of queue)

**Comment by Blade2021** [comment]
Splitting the rest of this issue into individual parts.
