### ISSUE TITLE
Sherlock v2 Checklist

### ISSUE THREAD

**Issue by Blade2021** [Blade2021/Sherlock#22]
**SHERLOCK V2 CHECKLIST**

- [x] Log Channel Functions
- [x] Change Prefix
- [x] Self Roles
- [x] Word Filtering
- [ ] Embed Filtering
- [x] Welcome Messages
- [x] Moderator Roles
- [x] Channel Exceptions
- [x] Leave
- [ ] Muting
- [ ] Timed Events
- [x] Infractions
- [x] Auto Roles
- [x] Commands (command)
- [x] Spam Filtering
- [x] Discord Link Filtering
- [x] Mothership Notifications
- [x] Thread support
- [x] Subscriber Commands
- [x] Unban Command
- [x] Ignore Channel

**Documentation:**
- [ ] Help docs for commands verified

**REMOVED COMMANDS**
- Channel Cooldown
- Archive Category

**Comment by Blade2021** [comment]
Closed due to inactivity.  New list will be created for v3 conversion.
